package hr.terraforming.mars.terraformingmars.enums;

public enum ActionType {
    INITIAL_SETUP,
    PLAYER_ORDER,
    PLAY_CARD,
    PLACE_TILE,
    CLAIM_MILESTONE,
    FUND_AWARD,
    USE_STANDARD_PROJECT,
    CONVERT_HEAT,
    CONVERT_PLANTS,
    SELL_PATENTS,
    PASS_TURN,
    AUTO_PASS,
    RESEARCH_COMPLETE,
    OPEN_CHOOSE_CARDS_MODAL,
    OPEN_SELL_PATENTS_MODAL,
    OPEN_FINAL_GREENERY_MODAL,
    OPEN_PRODUCTION_PHASE_MODAL,
    FINISH_FINAL_GREENERY,
    FINISH_PRODUCTION_PHASE
}
