module hr.terraforming.mars.terraformingmars {
    requires javafx.controls;
    requires javafx.fxml;
    requires java.desktop;
    requires org.slf4j;
    requires com.google.gson;
    requires java.rmi;
    requires java.naming;
    requires static lombok;
    requires java.net.http;

    opens hr.terraforming.mars.terraformingmars to javafx.fxml;
    exports hr.terraforming.mars.terraformingmars;
    exports hr.terraforming.mars.terraformingmars.model;
    opens hr.terraforming.mars.terraformingmars.model to javafx.fxml;
    exports hr.terraforming.mars.terraformingmars.factory;
    opens hr.terraforming.mars.terraformingmars.factory to javafx.fxml;
    exports hr.terraforming.mars.terraformingmars.enums;
    opens hr.terraforming.mars.terraformingmars.enums to javafx.fxml;
    opens hr.terraforming.mars.terraformingmars.view to javafx.fxml;
    exports hr.terraforming.mars.terraformingmars.view;
    opens hr.terraforming.mars.terraformingmars.manager to javafx.fxml;
    exports hr.terraforming.mars.terraformingmars.manager;
    exports hr.terraforming.mars.terraformingmars.view.component;
    exports hr.terraforming.mars.terraformingmars.service;
    exports hr.terraforming.mars.terraformingmars.util;
    exports hr.terraforming.mars.terraformingmars.config;
    exports hr.terraforming.mars.terraformingmars.effect;
    exports hr.terraforming.mars.terraformingmars.replay;
    opens hr.terraforming.mars.terraformingmars.replay to javafx.fxml;
    exports hr.terraforming.mars.terraformingmars.jndi;
    opens hr.terraforming.mars.terraformingmars.jndi to javafx.fxml;
    exports hr.terraforming.mars.terraformingmars.chat to java.rmi;
    exports hr.terraforming.mars.terraformingmars.coordinator;
    opens hr.terraforming.mars.terraformingmars.coordinator to javafx.fxml;
    exports hr.terraforming.mars.terraformingmars.controller.setup;
    opens hr.terraforming.mars.terraformingmars.controller.setup to javafx.fxml;
    opens hr.terraforming.mars.terraformingmars.controller.game to javafx.fxml;
    exports hr.terraforming.mars.terraformingmars.controller.game;
    exports hr.terraforming.mars.terraformingmars.network.message;
}